sudo: required
services:
  - docker

before_install: 
  - docker build -t fifapes123/react-docker-CI-AWS -f Dockerfile.dev .
  
script: 
  - docker run -e CI=true fifapes123/react-docker-CI-AWS npm run test